# Generated by Django 2.1.2 on 2018-12-07 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schedule", "0011_auto_20180205_1127"),
        ("event", "0017_auto_20180922_0511"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpstreamResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("changes", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upstream_results",
                        to="event.Event",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upstream_results",
                        to="schedule.Schedule",
                    ),
                ),
            ],
        ),
    ]
